
== Mongoose

If you've worked with an object relational mapper before like
hibernate, activerecord, propel, eloquent etc, those things do to SQL
what mongoose does to mongoDB. Mongoose is an ODM or an object
document mapper. 

Using mongoDB straight from node is certainly workable and not that
painful. However, mongoose allows us to work with mongoDB with a lot
more ease and from a higher abstraction, specifically an object
oriented abstraction.

TODO: more reasons to use mongoose (a) enforces schema (b)
connnection pools etc


=== Basic usage

Before we can begin using mongoose, we need to pull the module via
npm.

....
npm install mongoose --save
....




.Mongoose Schema and Model
====
....
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

var employeeSchema = new Schema({
  name: {
    last: {type:String, required:true},
    first: {type:String, required:true},
    middle: {type:String, required:false}
  },
  contacts: {
    email: [
      { 
        address: {type:String, required:false}
      }
    ],
    phone: [
      {
        number: {type:String, required:false}
      }
    ]
  }
});

var Employee = mongoose.model('Employee', employeeSchema);
....
====


.Save a document using a model
====
....
mongoose.Promise = global.Promise; // <1>
mongoose.connect('mongodb://localhost/crm2'); // <2>

var empObj = new Employee({
  name: {
    last: 'Doe',
    first: 'John'
  },
  contacts: {
    email: {
      address: 'johndoe@gmail.com'
    },
    phone: {
      number: '12345'
    }
  }
    
});


empObj.save(); // <3>
mongoose.connection.close(); // <4>
....
====

<1> As of this writing, *mpromise*, which is the default promise
library of mongoose has been deprecated. This line replaces mongoose's
promise library with the default ES6 Promise library

<2> `crm2` is the name of database. It doesn't matter if this database
already exist, it will be created automatically if it doesn't exist
yet

<3> The `save` method is intelligent enough to use either `insert` or
`update`. If the document doesn't exist yet, it will be _saved_, if it
does exist, it will be _updated_

<4> Always clean up after yourself


