////
This is a sub chapter of intro-mongo-nosql.adoc
////

=== Basic Usage

*Starting the server*. On a terminal window, start the server by running the `mongod`
executable

----
mongod
----

*Connecting a client*. On another terminal window, start the mongo
client by running

----
mongo 
----

You should get the chevon prompt of mongodb after launching the client
successfully.

*To list all the databases*, use the command

----
> show databases
----

At this point, you won't see much because we haven't created any
databases of our own just yet. We'll do just that in the next section.

==== Creating Collections and Documents

If we were dealing with a relational database, before we can start
adding a record, we need to (1) create the datbase first (2) create
the tables and define its schema, only then can we (3) insert our
first record.

MongoDB is a schema-less database, we don't have to pre-define
anything before we can start adding records. 

....
mongo // <1>
> show databases // <2>
> use crm; // <3>
> db.clients.count(); // <4>
> 0 
....
<1> Start the mongo client, you need to make sure that you have
started the `mongod` server on another terminal before you invoke the
`mongo` command

<2> You've seen this from the previous section. This will list all the
existing databases in our system. At the moment, this won't show much

<3> The `use` command will switch databases. At the moment, we haven't
defined the _crm_ database yet, but that does not matter to mongo,
it will assume that you actually have that database and switch to it
anyway

<4> `db` is the alias for the currently used database, in our case,
db is an alias to the _crm_ database. You could think of this command
as `crm.clients.count()`, if that helps. The level of organization
next to the database is a collection (equivalent to a table in RDBMS).
so `db.clients` refers to a collection named _clients_ inside the crm
database. Again, we haven't defined any collections yet, but mongo is
very helpful and returns to us the number of records inside the
_clients_ collection anyway (which is zero of course)



Explain that we don't have to create the database or the table or any
document before hand. Explain that a mongoDB is structureless
database. And we only create these things we have actually inserted
the first document.



- Starting the server
- Connecting a client
- Listing all the databases
- Creating a database
- Create a collection
- Creating a document
- Finding a document
- Updating a document
- Deleting a document
- quit the client session
- quite the server



