////
This is a sub chapter of intro-mongo-nosql.adoc
////

=== Basic Usage

*Starting the server*. On a terminal window, start the server by running the `mongod`
executable

----
mongod
----

*Connecting a client*. On another terminal window, start the mongo
client by running

----
mongo 
----

You should get the chevon prompt of mongodb after launching the client
successfully.

*To list all the databases*, use the command

----
> show databases
----

At this point, you won't see much because we haven't created any
databases of our own just yet. We'll do just that in the next section.

==== Creating Collections and Documents

If we were dealing with a relational database, before we can start
adding a record, we need to (1) create the database first then (2) create
the tables and define its schema, only then can we (3) insert our
first record.

In mongoDB, we don't need to create a pre-defined schema because mongo
databases do not enforce schemas. Schemas are optional, you may or may
not want to use them. If ever you will use schemas, they are not
usually defined on the database level but are rather enforced at an
application level (nodejs). So we can just go ahead and create a
record (document) right away.

The command snippet below shows a session where we create a database
named _crm_.

....
mongo // <1>
> show databases // <2>
> use crm; // <3>
> db.clients.count(); // <4>
> 0 
....
<1> Start the mongo client, you need to make sure that you have
started the `mongod` server on another terminal before you invoke the
`mongo` command

<2> You've seen this from the previous section. This will list all the
existing databases in our system. At the moment, this won't show much

<3> The `use` command will switch databases. At the moment, we haven't
defined the _crm_ database yet, but that does not matter to mongo,
it will assume that you actually have that database and switch to it
anyway

<4> `db` is the alias for the currently used database, in our case,
db is an alias to the _crm_ database. You could think of this command
as `crm.clients.count()`, if that helps. The level of organization
next to the database is a collection (equivalent to a table in RDBMS).
so `db.clients` refers to a collection named _clients_ inside the crm
database. Again, we haven't defined any collections yet, but mongo is
very helpful and returns to us the number of records inside the
_clients_ collection anyway (which is zero of course)

Let's continue our session with the mongoDB REPL and try to insert
some documents on the _clients_ collection.

....
> db.clients.insert({name: “Air BnB”, contact_owner: “Ted Hagos”,
 contacts: [{name: “John Doe”, email: “johndoe@gmail.com”},
 {name:”Jane Doe”, email:”janedoe@gmail.com”}], projects:
 [{name:”project1”, status: “not moving”}, {name: “project2”}]})
....

The command snippet above maybe a bit ugly to look at, but if you
inspect it closely, the parameter of the `insert` method is a JSON
object, mongoDB documents are actually JSON objects.

Alternatively,we can create documents this way

....
> var doc = {} // <1>
> doc.name = “Air BnB” // <2>
> doc.contact_owner = “Ted Hagos” // <3>
> doc.contacts = [{name: “John Doe”, email: “johndoe@gmail.com”}, 
  {name:“Jane Doe”, email:“janedoe@gmail.com”}] // <4>
> doc.projects = [{name: “project1”, status: “not moving”}, {name:
  “project2”, status: “not moving”}] // <5>
> db.clients.save(doc) // <6>
....
<1> Create an empty JSON object and assign it variable `doc`

<2> Create a property named `name`, attach it to the `doc` object. We
assign it a value of "Air BnB"

<3> Create a property named `contact_owner`, we assign it a string
value of "Ted Hagos"

<4> Create a property named `contacts`, this is an array object which
contains two JSON elements

<5> Create a property named `projects`, like `contacts`, this is also
an array object

<6> The `save` method performs an insert action as well

MongoDB documents are just JSON objects, so you can pretty much
compose the documents as object literals.


==== Finding a document

==== Updating a document

==== Deleting a document

==== Quitting the mongo REPL

==== Quitting the mongod server

==== SQL commands vs mongoDB commands







