
== Mongoose

If you've worked with an object relational mapper before like
hibernate, activerecord, propel, eloquent etc, those things do to SQL
what mongoose does to mongoDB. Mongoose is an ODM or an object
document mapper. 

Using mongoDB straight from node is certainly workable and not that
painful. However, mongoose allows us to work with mongoDB with a lot
more ease and from a higher abstraction, specifically an object
oriented abstraction.

TODO: more reasons to use mongoose (a) enforces schema (b)
connnection pools etc


=== Basic usage

Before we can begin using mongoose, we need to pull the module via
npm.

....
npm install mongoose --save
....

The next thing to do is to create a schema for each of our
collection. MongoDB itself does not require a schema, so you might be
wondering why are putting this self-imposed constraint upon ourselves?
That may seem counter-intuitive doesn't it? But a schema makes your life a bit
more sane as a developer. Imagine working with a collection that
doesn't have a consistent structure. It is impractical to write
program logic for each document (record). The programming idiom for
database manipulation is that we process a set of records from top to
bottom, we stop until there are no more records to process. This would
be fairly difficult to do if the structure of our documents are not
consistent. So, most of the time, you need a schema. 


.Basic Schema and Model
====
....
const mongoose = require('mongoose'); // <1>
const Schema  = mongoose.Schema; // <2>

var personSchema = new Schema({ // <3>
  lastname: {type: String, required: true}, // <4>
  firstname: {type:String, required:true},
  middlename : {type:String, required:false}
});

var Person = mongoose.model('Person', personSchema); // <5> <6>
....
====

<1> Like all other modules, we need to require it in our app before we
can use it

<2> Get the Schema constructor

<3> When creating a new Schema, we just need to pass a JSON literal to
its constructor. This JSON literal becomes the structure of a document
or record

<4>   

<5>

<6>



http://mongoosejs.com/docs/connections.html
http://mongoosejs.com/docs/schematypes.html
http://mongoosejs.com/docs/models.html

.Data types of Mongoose




.Mongoose Schema and Model
====
....
const mongoose = require('mongoose'); // 
const Schema = mongoose.Schema; 

var employeeSchema = new Schema({ // 
  name: {
    last: {type:String, required:true},
    first: {type:String, required:true},
    middle: {type:String, required:false}
  },
  contacts: {
    email: [
      { 
        address: {type:String, required:false}
      }
    ],
    phone: [
      {
        number: {type:String, required:false}
      }
    ]
  }
});

var Employee = mongoose.model('Employee', employeeSchema);
....
====


.Save a document using a model
====
....
mongoose.Promise = global.Promise; // <1>
mongoose.connect('mongodb://localhost/crm2'); // <2>

var empObj = new Employee({
  name: {
    last: 'Doe',
    first: 'John'
  },
  contacts: {
    email: {
      address: 'johndoe@gmail.com'
    },
    phone: {
      number: '12345'
    }
  }
    
});


empObj.save(); // <3>
mongoose.connection.close(); // <4>
....
====

<1> As of this writing, *mpromise*, which is the default promise
library of mongoose has been deprecated. This line replaces mongoose's
promise library with the default ES6 Promise library

<2> `crm2` is the name of database. It doesn't matter if this database
already exist, it will be created automatically if it doesn't exist
yet

<3> The `save` method is intelligent enough to use either `insert` or
`update`. If the document doesn't exist yet, it will be _saved_, if it
does exist, it will be _updated_

<4> Always clean up after yourself


